-- ============================================================
-- SIKLAB COMPLETE SUPABASE SCHEMA
-- Run once in Supabase SQL Editor on a NEW project.
-- ============================================================
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.school_years (
    year_id bigint generated by default as identity primary key,
    label varchar(20) not null unique,
    is_active boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.student (
    student_id bigint generated by default as identity primary key,
    lrn varchar(12) unique,
    first_name varchar(50) not null,
    last_name varchar(50) not null,
    section varchar(50) default 'Grade 3 - Mabini',
    grade_level integer not null default 3,
    school_year_id bigint references public.school_years(year_id) on delete set null,
    created_at timestamptz not null default now(),
    constraint student_lrn_12_digits check (lrn is null or lrn ~ '^[0-9]{12}$')
);

create table if not exists public.custom_game_module (
    game_id bigint generated by default as identity primary key,
    quarter integer not null default 1 check (quarter between 1 and 4),
    game_name varchar(150) not null,
    file_path varchar(255) not null,
    is_editable boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.custom_question (
    question_id bigint generated by default as identity primary key,
    game_module varchar(50) not null,
    prompt text not null,
    correct_ans integer not null check (correct_ans between 0 and 4),
    time_limit integer not null default 10 check (time_limit > 0),
    image_url text,
    created_at timestamptz not null default now()
);

create table if not exists public.game_settings (
    setting_id bigint generated by default as identity primary key,
    game_module varchar(50) not null unique,
    settings_json jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.lesson_modules (
    module_id bigint generated by default as identity primary key,
    week_id integer not null,
    school_year_id bigint not null references public.school_years(year_id) on delete cascade,
    label varchar(50),
    title varchar(150) not null,
    subtitle varchar(255),
    icon varchar(50) default 'fa-book-open',
    color varchar(50) default 'blue',
    completion_type varchar(20) default 'quiz' check (completion_type in ('quiz','view')),
    lesson_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (school_year_id, week_id)
);

create table if not exists public.student_group_set (
    set_id bigint generated by default as identity primary key,
    school_year_id bigint not null references public.school_years(year_id) on delete cascade,
    set_label varchar(20) not null,
    group_data jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default now(),
    unique (school_year_id, set_label)
);

create table if not exists public.student_progress (
    progress_id bigint generated by default as identity primary key,
    student_name varchar(100) not null unique,
    stars integer not null default 0,
    unlocked_weeks jsonb not null default '[1]'::jsonb,
    updated_at timestamptz not null default now()
);

create table if not exists public.game_type (
    game_type_id bigint generated by default as identity primary key,
    name varchar(100) not null,
    mechanics_config jsonb,
    requires_questions boolean default true
);

create table if not exists public.topic (
    topic_id bigint generated by default as identity primary key,
    teacher_user_id uuid references auth.users(id) on delete set null,
    week_number integer not null,
    day_number integer not null,
    title varchar(150)
);

create table if not exists public.game_session (
    session_id bigint generated by default as identity primary key,
    game_type_id bigint references public.game_type(game_type_id) on delete set null,
    topic_id bigint references public.topic(topic_id) on delete set null,
    played_at timestamptz not null default now()
);

create table if not exists public.question (
    question_id bigint generated by default as identity primary key,
    topic_id bigint references public.topic(topic_id) on delete cascade,
    game_type_id bigint references public.game_type(game_type_id) on delete set null,
    prompt text not null,
    asset_url text,
    time_limit_sec integer default 10
);

create table if not exists public.question_option (
    option_id bigint generated by default as identity primary key,
    question_id bigint references public.question(question_id) on delete cascade,
    option_text varchar(100) not null,
    is_correct boolean default false,
    hardware_button_map integer not null
);

create table if not exists public.iot_device (
    mac_address varchar(32) primary key,
    assigned_player varchar(20),
    status varchar(20) default 'Active'
);

create table if not exists public.player_score (
    score_id bigint generated by default as identity primary key,
    session_id bigint references public.game_session(session_id) on delete cascade,
    student_id bigint references public.student(student_id) on delete cascade,
    mac_address varchar(32) references public.iot_device(mac_address) on delete set null,
    final_score integer default 0,
    highest_combo integer default 1,
    correct_answers integer default 0,
    wrong_answers integer default 0,
    avg_reaction_time_ms integer,
    custom_game_data jsonb,
    created_at timestamptz not null default now()
);

create table if not exists public.player_response (
    response_id bigint generated by default as identity primary key,
    session_id bigint references public.game_session(session_id) on delete cascade,
    student_id bigint references public.student(student_id) on delete cascade,
    question_id bigint references public.question(question_id) on delete cascade,
    selected_option_id bigint references public.question_option(option_id) on delete set null,
    is_correct boolean,
    reaction_time_ms integer,
    created_at timestamptz not null default now()
);

create table if not exists public.controller_devices (
    device_id text primary key,
    assigned_player text not null check (assigned_player in ('player1','player2')),
    device_token_hash text not null,
    enabled boolean not null default true,
    last_state text check (last_state is null or last_state ~ '^[01]{9}$'),
    last_seen timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists uq_controller_active_player
    on public.controller_devices (assigned_player)
    where enabled = true;

-- RLS
alter table public.school_years enable row level security;
alter table public.student enable row level security;
alter table public.custom_game_module enable row level security;
alter table public.custom_question enable row level security;
alter table public.game_settings enable row level security;
alter table public.lesson_modules enable row level security;
alter table public.student_group_set enable row level security;
alter table public.student_progress enable row level security;
alter table public.game_type enable row level security;
alter table public.topic enable row level security;
alter table public.game_session enable row level security;
alter table public.question enable row level security;
alter table public.question_option enable row level security;
alter table public.iot_device enable row level security;
alter table public.player_score enable row level security;
alter table public.player_response enable row level security;
alter table public.controller_devices enable row level security;

do $$
declare t text;
begin
    foreach t in array array[
        'school_years','student','custom_game_module','custom_question',
        'game_settings','lesson_modules','student_group_set','student_progress',
        'game_type','topic','game_session','question','question_option',
        'iot_device','player_score','player_response'
    ]
    loop
        execute format('drop policy if exists "teacher full access" on public.%I', t);
        execute format('create policy "teacher full access" on public.%I for all to authenticated using (true) with check (true)', t);
    end loop;
end $$;

drop policy if exists "authenticated users can read controller status" on public.controller_devices;
create policy "authenticated users can read controller status"
    on public.controller_devices for select to authenticated using (true);

-- Storage buckets
insert into storage.buckets (id, name, public)
values ('question-images','question-images',true),
       ('lesson-images','lesson-images',true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "public can view SikLab images" on storage.objects;
create policy "public can view SikLab images"
    on storage.objects for select to public
    using (bucket_id in ('question-images','lesson-images'));

drop policy if exists "teachers can upload SikLab images" on storage.objects;
create policy "teachers can upload SikLab images"
    on storage.objects for insert to authenticated
    with check (bucket_id in ('question-images','lesson-images'));

drop policy if exists "teachers can update SikLab images" on storage.objects;
create policy "teachers can update SikLab images"
    on storage.objects for update to authenticated
    using (bucket_id in ('question-images','lesson-images'))
    with check (bucket_id in ('question-images','lesson-images'));

drop policy if exists "teachers can delete SikLab images" on storage.objects;
create policy "teachers can delete SikLab images"
    on storage.objects for delete to authenticated
    using (bucket_id in ('question-images','lesson-images'));

-- Safe lesson reorder
create or replace function public.reorder_lessons(
    p_school_year_id bigint,
    p_module_ids bigint[]
)
returns void
language plpgsql
security invoker
set search_path = public
as $$
declare
    v_module_id bigint;
    v_position integer := 1;
begin
    if auth.uid() is null then raise exception 'Authentication required'; end if;

    foreach v_module_id in array p_module_ids loop
        update public.lesson_modules
        set week_id = -100000 - v_position, updated_at = now()
        where module_id = v_module_id and school_year_id = p_school_year_id;
        if not found then
            raise exception 'Lesson % does not belong to school year %', v_module_id, p_school_year_id;
        end if;
        v_position := v_position + 1;
    end loop;

    v_position := 1;
    foreach v_module_id in array p_module_ids loop
        update public.lesson_modules
        set week_id = v_position,
            lesson_json = jsonb_set(coalesce(lesson_json,'{}'::jsonb), '{week_id}', to_jsonb(v_position), true),
            updated_at = now()
        where module_id = v_module_id and school_year_id = p_school_year_id;
        v_position := v_position + 1;
    end loop;
end;
$$;
grant execute on function public.reorder_lessons(bigint,bigint[]) to authenticated;

-- Controller provisioning
create or replace function public.provision_controller(p_device_id text, p_player text)
returns table(device_id text, assigned_player text, device_token text)
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
    v_device_id text := upper(trim(p_device_id));
    v_token text := encode(extensions.gen_random_bytes(32), 'hex');
    v_hash text := encode(extensions.digest(v_token, 'sha256'), 'hex');
begin
    if v_device_id !~ '^[A-F0-9]{6,32}$' then raise exception 'Invalid device id'; end if;
    if p_player not in ('player1','player2') then raise exception 'Player must be player1 or player2'; end if;

    update public.controller_devices
       set enabled = false, updated_at = now()
     where assigned_player = p_player
       and device_id <> v_device_id
       and enabled = true;

    insert into public.controller_devices(device_id,assigned_player,device_token_hash,enabled,updated_at)
    values(v_device_id,p_player,v_hash,true,now())
    on conflict(device_id) do update
       set assigned_player=excluded.assigned_player,
           device_token_hash=excluded.device_token_hash,
           enabled=true,
           updated_at=now();

    return query select v_device_id,p_player,v_token;
end;
$$;
revoke all on function public.provision_controller(text,text) from public;
revoke all on function public.provision_controller(text,text) from anon;
revoke all on function public.provision_controller(text,text) from authenticated;

create or replace function public.disable_controller(p_device_id text)
returns void
language sql
security definer
set search_path = public
as $$
    update public.controller_devices
    set enabled=false, updated_at=now()
    where device_id=upper(trim(p_device_id));
$$;
revoke all on function public.disable_controller(text) from public;
revoke all on function public.disable_controller(text) from anon;
revoke all on function public.disable_controller(text) from authenticated;

-- Default Week 1 game
insert into public.custom_game_module(quarter,game_name,file_path,is_editable)
select 1,'Week 1: Sense Detectives','games/SikLab_Sense_Detectives_W1_SUPABASE.html',false
where not exists (
    select 1 from public.custom_game_module
    where file_path='games/SikLab_Sense_Detectives_W1_SUPABASE.html'
);
