-- Install after the existing SikLab school-year and AI migrations.
-- Keeps existing questions; connects legacy Tug questions to school-year topics.
create table if not exists public.game_question_topics (
    topic_id bigint generated by default as identity primary key,
    school_year_id bigint not null references public.school_years(year_id) on delete cascade,
    game_module varchar(50) not null,
    topic_name varchar(80) not null,
    description varchar(220),
    icon text,
    is_active boolean not null default true,
    game_config jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.game_question_topics add column if not exists game_config jsonb not null default '{}'::jsonb;
alter table public.game_question_topics drop constraint if exists game_question_topics_game_module_check;
alter table public.custom_question add column if not exists topic_id bigint;
-- Tug uses four physical answer buttons; the other integrated games use five.
alter table public.custom_question drop constraint if exists custom_question_answer_options_check;
alter table public.custom_question add constraint custom_question_answer_options_check
check (answer_options is null or (jsonb_typeof(answer_options)='array' and
    jsonb_array_length(answer_options) = case when game_module='TUG' then 4 else 5 end));
create index if not exists idx_siklab_tug_topics on public.game_question_topics(school_year_id,game_module);
create index if not exists idx_siklab_tug_questions on public.custom_question(school_year_id,game_module,topic_id);
alter table public.game_question_topics enable row level security;
grant select,insert,update,delete on public.game_question_topics to authenticated;
grant usage,select on all sequences in schema public to authenticated;
do $$ begin
    if not exists(select 1 from pg_policies where schemaname='public' and tablename='game_question_topics' and policyname='siklab_teacher_topics') then
        create policy siklab_teacher_topics on public.game_question_topics
        for all to authenticated using (public.is_approved_teacher()) with check (public.is_approved_teacher());
    end if;
end $$;

-- Group existing Tug questions by their saved topic text without deleting them.
insert into public.game_question_topics (school_year_id,game_module,topic_name,icon,is_active)
select distinct cq.school_year_id, 'TUG', coalesce(nullif(left(trim(cq.topic),80),''),'General Science'), '🧋', true
from public.custom_question cq
where cq.game_module='TUG' and cq.school_year_id is not null
  and not exists (select 1 from public.game_question_topics t
                  where t.school_year_id=cq.school_year_id and t.game_module='TUG'
                    and lower(t.topic_name)=lower(coalesce(nullif(left(trim(cq.topic),80),''),'General Science')));
update public.custom_question cq
set topic_id = t.topic_id, topic = t.topic_name, question_set = t.topic_name
from public.game_question_topics t
where cq.game_module='TUG' and cq.topic_id is null and cq.school_year_id=t.school_year_id
  and t.game_module='TUG'
  and lower(t.topic_name)=lower(coalesce(nullif(left(trim(cq.topic),80),''),'General Science'));

create or replace function public.copy_school_year_content(
    p_source_year_id bigint,
    p_target_year_id bigint,
    p_copy_lessons boolean default true,
    p_copy_questions boolean default true,
    p_copy_settings boolean default true,
    p_mode text default 'merge'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_lessons integer := 0;
    v_questions integer := 0;
    v_settings integer := 0;
    v_topics integer := 0;
    v_mode text := lower(trim(coalesce(p_mode, 'merge')));
begin
    if not public.is_approved_teacher() then
        raise exception 'Approved teacher account required';
    end if;

    if p_source_year_id is null or p_target_year_id is null then
        raise exception 'Source and target school years are required';
    end if;

    if p_source_year_id = p_target_year_id then
        raise exception 'Source and target school years must be different';
    end if;

    if v_mode not in ('merge', 'replace') then
        raise exception 'Copy mode must be merge or replace';
    end if;

    if not exists(select 1 from public.school_years where year_id = p_source_year_id) then
        raise exception 'Source school year does not exist';
    end if;

    if not exists(select 1 from public.school_years where year_id = p_target_year_id) then
        raise exception 'Target school year does not exist';
    end if;

    if p_copy_lessons then
        if v_mode = 'replace' then
            delete from public.lesson_modules where school_year_id = p_target_year_id;
        end if;

        insert into public.lesson_modules(
            week_id,
            school_year_id,
            label,
            title,
            subtitle,
            icon,
            color,
            completion_type,
            lesson_json,
            is_published,
            published_at,
            created_at,
            updated_at
        )
        select
            src.week_id,
            p_target_year_id,
            src.label,
            src.title,
            src.subtitle,
            src.icon,
            src.color,
            src.completion_type,
            case
                when jsonb_typeof(src.lesson_json) = 'object'
                    then jsonb_set(src.lesson_json, '{year_id}', to_jsonb(p_target_year_id), true)
                else src.lesson_json
            end,
            src.is_published,
            case when src.is_published then now() else null end,
            now(),
            now()
        from public.lesson_modules src
        where src.school_year_id = p_source_year_id
        on conflict (school_year_id, week_id) do nothing;

        get diagnostics v_lessons = row_count;
    end if;

    if p_copy_questions then
        if v_mode = 'replace' then
            delete from public.custom_question where school_year_id = p_target_year_id;
            delete from public.game_question_topics where school_year_id = p_target_year_id;
        end if;

        insert into public.game_question_topics
            (school_year_id,game_module,topic_name,description,icon,is_active,game_config)
        select p_target_year_id, src.game_module, src.topic_name, src.description,
               src.icon, src.is_active, src.game_config
        from public.game_question_topics src
        where src.school_year_id = p_source_year_id
          and not exists (
              select 1 from public.game_question_topics dst
              where dst.school_year_id = p_target_year_id and dst.game_module = src.game_module
                and lower(dst.topic_name) = lower(src.topic_name)
          );
        get diagnostics v_topics = row_count;

        insert into public.custom_question(
            school_year_id,
            game_module,
            prompt,
            correct_ans,
            time_limit,
            image_url,
            answer_options, topic_id,
            question_set, explanation, topic, source_type, source_label, lesson_module_id,
            image_query, image_attribution, image_license, image_source, ai_generated, review_status,
            created_at
        )
        select
            p_target_year_id,
            src.game_module,
            src.prompt,
            src.correct_ans,
            src.time_limit,
            src.image_url,
            src.answer_options,
            (select dst.topic_id from public.game_question_topics dst
             join public.game_question_topics original on original.topic_id = src.topic_id
             where dst.school_year_id = p_target_year_id
               and dst.game_module = src.game_module
               and lower(dst.topic_name) = lower(original.topic_name)
             limit 1),
            src.question_set, src.explanation, src.topic, src.source_type, src.source_label,
            (select dst.module_id from public.lesson_modules dst
             join public.lesson_modules original on original.module_id = src.lesson_module_id
             where dst.school_year_id = p_target_year_id and dst.week_id = original.week_id limit 1),
            src.image_query, src.image_attribution, src.image_license, src.image_source,
            src.ai_generated, src.review_status,
            now()
        from public.custom_question src
        where src.school_year_id = p_source_year_id
          and (
              v_mode = 'replace'
              or not exists (
                  select 1
                  from public.custom_question existing
                  where existing.school_year_id = p_target_year_id
                    and existing.game_module = src.game_module
                    and existing.prompt = src.prompt
                    and existing.correct_ans = src.correct_ans
              )
          );

        get diagnostics v_questions = row_count;
    end if;

    if p_copy_settings then
        if v_mode = 'replace' then
            delete from public.game_settings where school_year_id = p_target_year_id;
        end if;

        insert into public.game_settings(
            school_year_id,
            game_module,
            settings_json,
            updated_at
        )
        select
            p_target_year_id,
            src.game_module,
            src.settings_json,
            now()
        from public.game_settings src
        where src.school_year_id = p_source_year_id
        on conflict (school_year_id, game_module) do nothing;

        get diagnostics v_settings = row_count;
    end if;

    return jsonb_build_object(
        'source_year_id', p_source_year_id,
        'target_year_id', p_target_year_id,
        'mode', v_mode,
        'lessons_copied', v_lessons,
        'questions_copied', v_questions,
        'topics_copied', v_topics,
        'settings_copied', v_settings
    );
end;
$$;

revoke all on function public.copy_school_year_content(bigint,bigint,boolean,boolean,boolean,text) from public;
grant execute on function public.copy_school_year_content(bigint,bigint,boolean,boolean,boolean,text) to authenticated;
